// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/404": {
    params: {};
  };
  "/": {
    params: {};
  };
  "/projects/single_power_screw/connections": {
    params: {};
  };
  "/projects/single_power_screw/components": {
    params: {};
  };
  "/projects/single_power_screw": {
    params: {};
  };
  "/projects/bell_bracket": {
    params: {};
  };
  "/single-power-screw-page": {
    params: {};
  };
  "/projects/rod_cap": {
    params: {};
  };
  "/bell-bracket-page": {
    params: {};
  };
  "/projects-page": {
    params: {};
  };
  "/rod-cap-page": {
    params: {};
  };
  "/about-page": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "routes/[404]._index.jsx": {
    id: "404";
    page: "/404";
  } | {
    id: "routes/[404]._index";
    page: "/*";
  };
  "root.jsx": {
    id: "root";
    page: "/404" | "/" | "/projects/single_power_screw/connections" | "/projects/single_power_screw/components" | "/projects/single_power_screw" | "/projects/bell_bracket" | "/single-power-screw-page" | "/projects/rod_cap" | "/bell-bracket-page" | "/projects-page" | "/rod-cap-page" | "/about-page" | "/projects" | "/about" | "/*";
  };
  "routes/[projects].[single_power_screw].[connections]._index.jsx": {
    id: "routes/[projects].[single_power_screw].[connections]._index";
    page: "/projects/single_power_screw/connections";
  };
  "routes/[projects].[single_power_screw].[components]._index.jsx": {
    id: "routes/[projects].[single_power_screw].[components]._index";
    page: "/projects/single_power_screw/components";
  };
  "routes/[projects].[single_power_screw]._index.jsx": {
    id: "routes/[projects].[single_power_screw]._index";
    page: "/projects/single_power_screw";
  };
  "routes/[projects].[bell_bracket]._index.jsx": {
    id: "routes/[projects].[bell_bracket]._index";
    page: "/projects/bell_bracket";
  };
  "routes/[single-power-screw-page]._index.jsx": {
    id: "routes/[single-power-screw-page]._index";
    page: "/single-power-screw-page";
  };
  "routes/[projects].[rod_cap]._index.jsx": {
    id: "routes/[projects].[rod_cap]._index";
    page: "/projects/rod_cap";
  };
  "routes/[bell-bracket-page]._index.jsx": {
    id: "routes/[bell-bracket-page]._index";
    page: "/bell-bracket-page";
  };
  "routes/[projects-page]._index.jsx": {
    id: "routes/[projects-page]._index";
    page: "/projects-page";
  };
  "routes/[rod-cap-page]._index.jsx": {
    id: "routes/[rod-cap-page]._index";
    page: "/rod-cap-page";
  };
  "routes/[about-page]._index.jsx": {
    id: "routes/[about-page]._index";
    page: "/about-page";
  };
  "routes/[projects]._index.jsx": {
    id: "routes/[projects]._index";
    page: "/projects";
  };
  "routes/[about]._index.jsx": {
    id: "routes/[about]._index";
    page: "/about";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
};