// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/404": {
    params: {};
  };
  "/": {
    params: {};
  };
  "/projects-page": {
    params: {};
  };
  "/about-page": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "routes/[404]._index.jsx": {
    id: "404";
    page: "/404";
  } | {
    id: "routes/[404]._index";
    page: "/*";
  };
  "root.jsx": {
    id: "root";
    page: "/404" | "/" | "/projects-page" | "/about-page" | "/projects" | "/about" | "/*";
  };
  "routes/[projects-page]._index.jsx": {
    id: "routes/[projects-page]._index";
    page: "/projects-page";
  };
  "routes/[about-page]._index.jsx": {
    id: "routes/[about-page]._index";
    page: "/about-page";
  };
  "routes/[projects]._index.jsx": {
    id: "routes/[projects]._index";
    page: "/projects";
  };
  "routes/[about]._index.jsx": {
    id: "routes/[about]._index";
    page: "/about";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
};